(lambda (pc) 
  (lambda (advice) 
    (lambda (f) 
      (lambda (a)
            (aroundapp (lambda (g)
                         (if (pc g)
                             (advice ((file "untag.rkt") g))
                             g))
                       (f a))))))
