(lambda (f) (lambda (a)
              (((((file "around.rkt") ((file "call.rkt") "fact"))
                 (lambda (proceed) (lambda (y) 
                                     (let ([result (proceed y)])
                                       (seq (write "y" y)
                                            (seq (write "result" result)
                                                 result))))))
                f)
               a)))