(lambda (pc) 
  (lambda (advice) 
    (lambda (f) 
      (lambda (a)
            (aroundapp (lambda (g)
                         (tagtest g
                                  (lambda (gtag) (lambda (gtagged)
                                                   (if (pc gtag)
                                                       (tag gtag (advice gtagged))
                                                       g)))
                                  g))
                       (f a))))))
