(lambda (f a)
  ((file "around.ttpl") 
   ((file "call.ttpl") 'fact)
   (lambda (proceed y) 
     (let ([result (proceed y)])
       (seq (write "y" (read "more input"))
            (seq (write "result" result)
                 result))))
   f a))
