(lambda (thunk)
  ((file "around.ttpl") 
   ((file "call.ttpl") 'fact_boxes)
   (lambda (proceed ybox) 
     (seq (write "y before" (unbox ybox))
          (let ([result (proceed ybox)])
            (seq (write "y after" (unbox ybox))
                 (seq (write "result" result)
                      result)))))
   thunk))
