(lambda (f a)
  ((file "examples/around.rkt") 
   ((file "examples/call.rkt") 'fact_boxes)
   (lambda (proceed ybox) 
     (seq (write "y before" (unbox ybox))
          (let ([result (proceed ybox)])
            (seq (write "y after" (unbox ybox))
                 (seq (write "result" result)
                      result)))))
   f
   a))