(lambda (f) (lambda (a)
              (((((file "around.ttpl") (lambda (jp) #t))
                 (lambda (proceed) (lambda (y) 
                                     (seq (write "call" proceed)
                                          (seq (write "arg" y)
                                               (proceed y))))))
                f)
               a)))
